// src/styles/lexical-editor-theme.ts
import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
    ltr: 'ltr',
    rtl: 'rtl',
    placeholder: 'editor-placeholder',
    paragraph: 'editor-paragraph',
    quote: 'editor-quote',
    heading: {
        h1: 'editor-h1',
        h2: 'editor-h2',
        h3: 'editor-h3',
        h4: 'editor-h4',
        h5: 'editor-h5',
        h6: 'editor-h6',
    },
    list: {
        nested: {
            listitem: 'editor-nested-listitem',
        },
        ol: 'editor-ol',
        ul: 'editor-ul',
        listitem: 'editor-listitem',
    },
    indent: 'editor-indent',
    excludeFromCopy: 'editor-excludeFromCopy',
    link: 'editor-link',
    text: {
        bold: 'editor-text-bold',
        italic: 'editor-text-italic',
        underline: 'editor-text-underline',
        strikethrough: 'editor-text-strikethrough',
        underlineStrikethrough: 'editor-text-underlineStrikethrough',
        code: 'editor-text-code',
        subscript: 'editor-text-subscript',
        superscript: 'editor-text-superscript',
        highlight: 'editor-text-highlight',
    },
    code: 'editor-code',
    codeHighlight: {
        atrule: 'editor-code-atrule',
        attr: 'editor-code-attr',
        boolean: 'editor-code-boolean',
        builtin: 'editor-code-builtin',
        cdata: 'editor-code-cdata',
        char: 'editor-code-char',
        attrComment: 'editor-code-attrComment',
        comment: 'editor-code-comment',
        class: 'editor-code-class',
        constant: 'editor-code-constant',
        deleted: 'editor-code-deleted',
        doctype: 'editor-code-doctype',
        entity: 'editor-code-entity',
        function: 'editor-code-function',
        important: 'editor-code-important',
        inserted: 'editor-code-inserted',
        keyword: 'editor-code-keyword',
        namespace: 'editor-code-namespace',
        number: 'editor-code-number',
        operator: 'editor-code-operator',
        prolog: 'editor-code-prolog',
        property: 'editor-code-property',
        punctuation: 'editor-code-punctuation',
        regex: 'editor-code-regex',
        selector: 'editor-code-selector',
        string: 'editor-code-string',
        symbol: 'editor-code-symbol',
        tag: 'editor-code-tag',
        url: 'editor-code-url',
        variable: 'editor-code-variable',
    },
    root: 'editor-root',
    // You can define other node classes here as needed
};

export default theme;